FROM tiangolo/uvicorn-gunicorn:python3.10

WORKDIR /app

COPY ./requirements.txt .

# RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app